version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=todolist
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=Password@123
      - MYSQL_ROOT_PASSWORD=Password@123
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/todolist?useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=appuser
      - SPRING_DATASOURCE_PASSWORD=Password@123
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
    depends_on:
      - db
volumes:
  db_data: {}

#version: '3.8'
#services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_APPLICATION_NAME=todolist
#      - SPRING_DATASOURCE_URL=jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS TODOLIST
#      - SPRING_DATASOURCE_USERNAME=sa
#      - SPRING_DATASOURCE_PASSWORD=sa
#      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.h2.Driver
