## CONFIGURACOES DO SPRING BOOT
spring:
  application:
    name: todolist
  datasource:
    url: jdbc:mysql://localhost:3306/todolist?useSSL=false&serverTimezone=UTC
    username: root
    password: Password@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  # Configuracoes do Flyway para migracoes de banco de dados
  flyway:
    enabled: false

server:
  port: 8080

## CONFIGURACOES DO SPRING BOOT ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

## CONFIGURACOES DA API
api:
  info:
    title: API TODOLIST
    description: API de Gerenciamento de tarefas
    version: 1.0.0
