## CONFIGURACOES DO SPRING BOOT
spring:
  application:
    name: todolist
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS TODOLIST
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080

## CONFIGURACOES DO SPRING BOOT ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

## CONFIGURACOES DA API
api:
  info:
    title: API TODOLIST
    description: API de Gerenciamento de tarefas
    version: 1.0.0
